### PR TITLE
plain_gray theme added

### PR DESCRIPTION
**Pull request by AhmetCanSolak**
I had little touches on kyren.css for a better visual taste.

### CODE REVIEW

**Comment by sarahxoxo** [comment]
It seems you edited other's css file(css/ariq.css).
Could you check what happened there?

**Comment by AhmetCanSolak** [comment]
@sarahxoxo I couldnt understand that but yes it seems like I changed another file which actually I didnot. Would you want me to close this PR and open a new one with proper submission?

**Comment by sarahxoxo** [comment]
You can just update your repository and the request will be updated automatically.
Don't forget to add your css file's name in index.html.

**Comment by AhmetCanSolak** [comment]
I've made some updates to fix it. Is it okay now?

**Comment by sarahxoxo** [comment]
It seems ok now!

**Pull request merged**
